import Head from "next/head";
import Image from "next/image";
import React from "react";
import styles from "../styles/Home.module.css";
import { supabaseClient } from "../utils/supabaseClient";
import Messages from "../components/Messages";
import DOMPurify from "dompurify";

export default function Home() {
  const [message, setMessage] = React.useState("");
  const [submitDisabled, setSubmitDisabled] = React.useState(true);

  const handleMessageChange = (e) => {
    if (e.target.value.trim().length > 0) {
      setSubmitDisabled(false);
    } else {
      setSubmitDisabled(true);
    }

    setMessage(DOMPurify.sanitize(e.target.value));
  };

  const handleSubmit = async (event) => {
    event.preventDefault();
    setSubmitDisabled(true);
    const { data, error } = await supabaseClient
      .from("messages")
      .insert({ message: message });

    if (!error) {
      console.log("Message received");
      setMessage("");
      setSubmitDisabled(true);
    }
  };

  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.main}>
        <Messages />
        <form onSubmit={handleSubmit}>
          <input
            type="text"
            className={styles.textInput}
            placeholder="Type to send a message"
            value={message}
            onChange={(e) => handleMessageChange(e)}
          />
          <button type="submit" disabled={submitDisabled}>
            Submit
          </button>
        </form>
      </main>
      <footer className={styles.footer}></footer>
    </div>
  );
}
